# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins: rubocop-rspec

AllCops:
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "log/**/*"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"
    - "tmp/**/*"
    - "vendor/**/*"
    - "Gemfile"
    - "Rakefile"

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
